### PR TITLE
UI/UX improvements + Quality of Life min width and height

### PR DESCRIPTION
**Pull request by Looskie**
Added acouple of things here, revolving more around the UI/UX portion.

This PR is basically just some UI/UX suggestions, if you want anything changed lmkk

P.s: Great application, just switched from tableplus to this and ughhh i love it sm.

also note, this is actually my first time working with VueJS, more of a NextJS/React type of guy myself, regardless, if there is some code quality issues also lmk so I can fix it up. very cool framework though! 

here is a list of things I've done

- Added a "close" button to almost if not all modals.
- Added a new button called "DangerButton" used for deleting things
- When deleting things, it will no longer use the PrimaryButton and rather use DangerButton
- Changed PrimaryButton's color to green-700 instead of red-700, when you're clicking an add button you'd expect it to be good and a green button :p 
- Added `cursor: pointer` to the tabs on server info
- Added a tooltip to the refresh button, at first I didn't know what it was for like 5 seconds.

### CODE REVIEW

**Comment by ekvedaras** [comment]
Hey. Really appreciate the effort! 🙂 CTA within color schemes with red accents is always tricky 🤔 I will check this tomorrow when I have access to my PC 👍

**Comment by Looskie** [comment]
> Hey. Really appreciate the effort! 🙂 CTA within color schemes with red accents is always tricky 🤔 I will check this tomorrow when I have access to my PC 👍

ohhhh, i seeee, the red was supposed to be the accent, okay! hmmm, perhaps we could find another way of implementing that? Otherwise I can revert those changes!

And sounds good ❤️ take your time!

**Comment by Looskie** [comment]
Also, perhaps you or I should add a prettierrc file? My default prettier config has got to one of the files because I accidentally pressed CTRL + S! So I think that would benefit a lot of contributors and keep the codebase neat and tidy. 

I would add it, but I don't know how you like your prettier config, so I could do that myself if you gave me the things you prefer

**Comment by ekvedaras** [comment]
Yeah, the accent was redis logo color. But I'll check, maybe that green one looks good as well. I will also add `.prettierrc` file. I was mostly using .editorconfig, but that mostly contains config for jetbrains ides :) Will merge this soon.

**Comment by Looskie** [comment]
> Yeah, the accent was redis logo color. But I'll check, maybe that green one looks good as well. I will also add `.prettierrc` file. I was mostly using .editorconfig, but that mostly contains config for jetbrains ides :) Will merge this soon.

Sounds good! I'll keep tinkering in the meantime to get the red accent back!❤️

**Comment by ekvedaras** [comment]
Ok, how does one use single quotes in js but double quotes in vue template? 🤔

**Comment by ekvedaras** [comment]
Could you also experiment with that green color a bit more? The current one feels kind of muted 🤷  Or bring back the previous one 😀 The rest is 👍

**Comment by Looskie** [comment]
> Ok, how does one use single quotes in js but double quotes in vue template with prettier? 🤔

I believe you cant actuallyyy. I could be wrong, Ill play around with ESlint + Prettier and tell you if i get a solution.

> Could you also experiment with that green color a bit more? The current one feels kind of muted 🤷 Or bring back the previous one 😀 The rest is 👍

Kk! Will do! I quite literally just replaced "red" with "green" so it stayed the same saturation/vibrance

**Comment by Looskie** [comment]
After attempting Eslint + prettier, i dont think its possible with vue, i think its possible with react/next but  thats through a plugin.

**Comment by Looskie** [comment]
Also, 
image
If I go to 600 its too dark imo, and if i go to 400 its too light, so i think 500 is the sweet spot, lmk

**Review by cnrad — APPROVED** [review]
LGTM! Nice work :)

**Review by ekvedaras — APPROVED** [review]
OK what about blue? 🤔 

image
image
image
image

Happy to go with either though. Could you add then a `.prettierrc`? I'm thinking a simple config would be fine. Maybe something like that:

```json
{
  "bracketSpacing": true,
  "printWidth": 120,
  "semi": false,
  "singleQuote": false,
  "trailingComma": "all",
}
```

Not super happy with `singleQuote: false`, but I think its better than having single quotes in HTML 😕
Could be integrated with this maybe: https://github.com/marketplace/actions/prettier-action#example-2-using-the-only_changed-or-same_commit-option-on-pr

Or I can do this step myself of course :)

**Comment by Looskie** [comment]
> OK what about blue? 🤔
> 
> image
> image
> image
> image
> 
> Happy to go with either though. Could you add then a `.prettierrc`? I'm thinking a simple config would be fine. Maybe something like that:
> 
> ```json
> {
>   "bracketSpacing": true,
>   "printWidth": 120,
>   "semi": false,
>   "singleQuote": false,
>   "trailingComma": "all",
> }
> ```
> 
> Not super happy with `singleQuote: false`, but I think its better than having single quotes in HTML 😕
> Could be integrated with this maybe: https://github.com/marketplace/actions/prettier-action#example-2-using-the-only_changed-or-same_commit-option-on-pr
> 
> Or I can do this step myself of course :)

YOOOO THAT BLUE IS LOWKEY FIRE, lets do that! and of course! I'll do that now.

What blue is that? Or did you mock that up? And are the blues different via light and dark mode?

**Comment by Looskie** [comment]
Ill be able to push these changes tomorrow evening, I'm currently at my girlfriends house, and my laptop just simply can not handle vue + electron development. poor 2012 mbp.

**Comment by ekvedaras** [comment]
I think it's simply `bg-blue-500`. Same color for both themes. No rush for anything, thank you for your effort 🥇

**Comment by Looskie** [comment]
Almost done! Just have to add the workflow now

**Comment by Looskie** [comment]
That should do that trick! lmk!

**Review by ekvedaras — APPROVED** [review]

**Comment by ekvedaras** [comment]
⭐ Thank you!

**Comment by alii** [comment]
image

# Thanks for merge

**Comment by bfu4** [comment]
## Thanks for merge

**Comment by Looskie** [comment]
image
<h3>Thanks for merge </h3>

**Comment by pxseu** [comment]
image
### Thanks for merge

**Pull request merged**
